/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ArticleMutation.graphql
 * @generated SignedSource<<967148c6fa19c6191db8b5cdcc4ecd24>>
 * @relayHash cd50eeb4b7198ef7f07af8e38692979d
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type ArticleMutationInput = {
  id?: ?string;
  keys?: ?string;
  values?: ?string;
  subEvents?: ?string;
  subNotes?: ?string;
  addEvents?: ?string;
  addNotes?: ?string;
  noteIndex?: ?number;
  noteIds?: ?string;
  noteValues?: ?string;
  eventIds?: ?string;
  eventValues?: ?string;
  submit?: ?boolean;
};

export type ArticleMutationResponse = {
  article?: ?ArticleMutationResponse_article;
  keys?: ?Array<?string>;
  newEvents?: ?Array<?ArticleMutationResponse_newEvents>;
  subEvents?: ?Array<?string>;
  updatedEvents?: ?Array<?ArticleMutationResponse_updatedEvents>;
};

export type ArticleMutationResponse_article = {
  id: string;
};

export type ArticleMutationResponse_newEvents_node = {
  id: string;
  text?: ?string;
};

export type ArticleMutationResponse_newEvents = {
  node?: ?ArticleMutationResponse_newEvents_node;
};

export type ArticleMutationResponse_updatedEvents_node = {
  id: string;
  text?: ?string;
};

export type ArticleMutationResponse_updatedEvents = {
  node?: ?ArticleMutationResponse_updatedEvents_node;
};
*/

/* eslint-disable comma-dangle, quotes */

/*
mutation ArticleMutation(
  $input: ArticleMutationInput!
) {
  saveArticle(input: $input) {
    article {
      id
    }
    keys
    newEvents {
      node {
        id
        text
      }
    }
    subEvents
    updatedEvents {
      node {
        id
        text
      }
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "ArticleMutationInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "ArticleMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "ArticleMutationInput!"
          }
        ],
        "concreteType": "ArticleMutationPayload",
        "name": "saveArticle",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Article",
            "name": "article",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "keys",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "EventEdge",
            "name": "newEvents",
            "plural": true,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "Event",
                "name": "node",
                "plural": false,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "text",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "subEvents",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "EventEdge",
            "name": "updatedEvents",
            "plural": true,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "Event",
                "name": "node",
                "plural": false,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "text",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "ArticleMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "ArticleMutationInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "ArticleMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "ArticleMutationInput!"
          }
        ],
        "concreteType": "ArticleMutationPayload",
        "name": "saveArticle",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Article",
            "name": "article",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "keys",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "EventEdge",
            "name": "newEvents",
            "plural": true,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "Event",
                "name": "node",
                "plural": false,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "text",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "subEvents",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "EventEdge",
            "name": "updatedEvents",
            "plural": true,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "Event",
                "name": "node",
                "plural": false,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "text",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation ArticleMutation(\n  $input: ArticleMutationInput!\n) {\n  saveArticle(input: $input) {\n    article {\n      id\n    }\n    keys\n    newEvents {\n      node {\n        id\n        text\n      }\n    }\n    subEvents\n    updatedEvents {\n      node {\n        id\n        text\n      }\n    }\n  }\n}\n"
};

module.exports = batch;
