/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DeleteMutation.graphql
 * @generated SignedSource<<59c43820ce74b61ef7f1fac5477cdee2>>
 * @relayHash 6bccd64c2cd882ecc141b5a592effa55
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type ArticleDeleteInput = {
  id?: ?string;
};

export type DeleteMutationResponse = {
  distroyedId?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

/*
mutation DeleteMutation(
  $input: ArticleDeleteInput!
) {
  articlDel(input: $input) {
    distroyedId
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "ArticleDeleteInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "DeleteMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "ArticleDeleteInput!"
          }
        ],
        "concreteType": "ArticleDeletePayload",
        "name": "articlDel",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "distroyedId",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "DeleteMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "ArticleDeleteInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "DeleteMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "ArticleDeleteInput!"
          }
        ],
        "concreteType": "ArticleDeletePayload",
        "name": "articlDel",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "distroyedId",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation DeleteMutation(\n  $input: ArticleDeleteInput!\n) {\n  articlDel(input: $input) {\n    distroyedId\n  }\n}\n"
};

module.exports = batch;
