/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DictionaryManager_viewer.graphql
 * @generated SignedSource<<cde1b3019a37f5f138100932fc953a63>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DictionaryManager_viewer = {
  id: string;
  dic?: ?DictionaryManager_viewer_dic;
};

export type DictionaryManager_viewer_dic_edges_node = {
  id: string;
  name?: ?string;
  order?: ?number;
};

export type DictionaryManager_viewer_dic_edges = {
  node?: ?DictionaryManager_viewer_dic_edges_node;
};

export type DictionaryManager_viewer_dic = {
  edges?: ?Array<?DictionaryManager_viewer_dic_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "code",
      "type": "String"
    },
    {
      "kind": "RootArgument",
      "name": "count",
      "type": "Int"
    }
  ],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": "count",
        "cursor": null,
        "direction": "forward",
        "path": [
          "dic"
        ]
      }
    ]
  },
  "name": "DictionaryManager_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": "dic",
      "args": [
        {
          "kind": "Variable",
          "name": "code",
          "variableName": "code",
          "type": "String"
        }
      ],
      "concreteType": "DictionaryConnection",
      "name": "__DictionaryManager_dic_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DictionaryEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Dictionary",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "order",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
