/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Filters_viewer.graphql
 * @generated SignedSource<<94774004e5c12a67a09b9983bb254f80>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Filters_viewer = {
  categories?: ?Filters_viewer_categories;
  jobs?: ?Filters_viewer_jobs;
  genders?: ?Filters_viewer_genders;
  marriages?: ?Filters_viewer_marriages;
  educations?: ?Filters_viewer_educations;
};

export type Filters_viewer_categories_edges_node = {
  id: string;
  name?: ?string;
  order?: ?number;
};

export type Filters_viewer_categories_edges = {
  node?: ?Filters_viewer_categories_edges_node;
};

export type Filters_viewer_categories = {
  edges?: ?Array<?Filters_viewer_categories_edges>;
};

export type Filters_viewer_jobs_edges_node = {
  id: string;
  name?: ?string;
  order?: ?number;
};

export type Filters_viewer_jobs_edges = {
  node?: ?Filters_viewer_jobs_edges_node;
};

export type Filters_viewer_jobs = {
  edges?: ?Array<?Filters_viewer_jobs_edges>;
};

export type Filters_viewer_genders_edges_node = {
  id: string;
  name?: ?string;
  order?: ?number;
};

export type Filters_viewer_genders_edges = {
  node?: ?Filters_viewer_genders_edges_node;
};

export type Filters_viewer_genders = {
  edges?: ?Array<?Filters_viewer_genders_edges>;
};

export type Filters_viewer_marriages_edges_node = {
  id: string;
  name?: ?string;
  order?: ?number;
};

export type Filters_viewer_marriages_edges = {
  node?: ?Filters_viewer_marriages_edges_node;
};

export type Filters_viewer_marriages = {
  edges?: ?Array<?Filters_viewer_marriages_edges>;
};

export type Filters_viewer_educations_edges_node = {
  id: string;
  name?: ?string;
  order?: ?number;
};

export type Filters_viewer_educations_edges = {
  node?: ?Filters_viewer_educations_edges_node;
};

export type Filters_viewer_educations = {
  edges?: ?Array<?Filters_viewer_educations_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "count",
      "type": "Int"
    }
  ],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": "count",
        "cursor": null,
        "direction": "forward",
        "path": [
          "categories"
        ]
      },
      {
        "count": "count",
        "cursor": null,
        "direction": "forward",
        "path": [
          "jobs"
        ]
      },
      {
        "count": "count",
        "cursor": null,
        "direction": "forward",
        "path": [
          "genders"
        ]
      },
      {
        "count": "count",
        "cursor": null,
        "direction": "forward",
        "path": [
          "marriages"
        ]
      },
      {
        "count": "count",
        "cursor": null,
        "direction": "forward",
        "path": [
          "educations"
        ]
      }
    ]
  },
  "name": "Filters_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "categories",
      "args": [
        {
          "kind": "Literal",
          "name": "code",
          "value": "Category",
          "type": "String"
        }
      ],
      "concreteType": "DictionaryConnection",
      "name": "__Filters_categories_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DictionaryEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Dictionary",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "order",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "__Filters_categories_connection{\"code\":\"Category\"}"
    },
    {
      "kind": "LinkedField",
      "alias": "jobs",
      "args": [
        {
          "kind": "Literal",
          "name": "code",
          "value": "Job",
          "type": "String"
        }
      ],
      "concreteType": "DictionaryConnection",
      "name": "__Filters_jobs_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DictionaryEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Dictionary",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "order",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "__Filters_jobs_connection{\"code\":\"Job\"}"
    },
    {
      "kind": "LinkedField",
      "alias": "genders",
      "args": [
        {
          "kind": "Literal",
          "name": "code",
          "value": "Gender",
          "type": "String"
        }
      ],
      "concreteType": "DictionaryConnection",
      "name": "__Filters_genders_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DictionaryEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Dictionary",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "order",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "__Filters_genders_connection{\"code\":\"Gender\"}"
    },
    {
      "kind": "LinkedField",
      "alias": "marriages",
      "args": [
        {
          "kind": "Literal",
          "name": "code",
          "value": "Marriage",
          "type": "String"
        }
      ],
      "concreteType": "DictionaryConnection",
      "name": "__Filters_marriages_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DictionaryEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Dictionary",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "order",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "__Filters_marriages_connection{\"code\":\"Marriage\"}"
    },
    {
      "kind": "LinkedField",
      "alias": "educations",
      "args": [
        {
          "kind": "Literal",
          "name": "code",
          "value": "Education",
          "type": "String"
        }
      ],
      "concreteType": "DictionaryConnection",
      "name": "__Filters_educations_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DictionaryEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Dictionary",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "order",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "__Filters_educations_connection{\"code\":\"Education\"}"
    }
  ],
  "type": "User"
};

module.exports = fragment;
