/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule QuyuProvince_viewer.graphql
 * @generated SignedSource<<7b92a679a16f9e5723997ee69eba696b>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type QuyuProvince_viewer = {
  id: string;
  provinces?: ?QuyuProvince_viewer_provinces;
};

export type QuyuProvince_viewer_provinces_edges_node = {
  id: string;
  name?: ?string;
  code?: ?string;
  isLeaf?: ?boolean;
};

export type QuyuProvince_viewer_provinces_edges = {
  node?: ?QuyuProvince_viewer_provinces_edges_node;
};

export type QuyuProvince_viewer_provinces = {
  edges?: ?Array<?QuyuProvince_viewer_provinces_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "QuyuProvince_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 50,
          "type": "Int"
        }
      ],
      "concreteType": "QuyuConnection",
      "name": "provinces",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "QuyuEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Quyu",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "code",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "isLeaf",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "provinces{\"first\":50}"
    }
  ],
  "type": "User"
};

module.exports = fragment;
