/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule QuyuProvinceQuery.graphql
 * @generated SignedSource<<6308747ccb58124e2b1a77f665e6579e>>
 * @relayHash fc56133346f4605a16e32d2ce1af40b2
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query QuyuProvinceQuery {
  viewer {
    id
    ...QuyuProvince_viewer
  }
}

fragment QuyuProvince_viewer on User {
  id
  provinces(first: 50) {
    edges {
      node {
        id
        name
        code
        isLeaf
      }
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "QuyuProvinceQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "FragmentSpread",
            "name": "QuyuProvince_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "QuyuProvinceQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "QuyuProvinceQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "first",
                "value": 50,
                "type": "Int"
              }
            ],
            "concreteType": "QuyuConnection",
            "name": "provinces",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "QuyuEdge",
                "name": "edges",
                "plural": true,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "Quyu",
                    "name": "node",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "id",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "name",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "code",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "isLeaf",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": "provinces{\"first\":50}"
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query QuyuProvinceQuery {\n  viewer {\n    id\n    ...QuyuProvince_viewer\n  }\n}\n\nfragment QuyuProvince_viewer on User {\n  id\n  provinces(first: 50) {\n    edges {\n      node {\n        id\n        name\n        code\n        isLeaf\n      }\n    }\n  }\n}\n"
};

module.exports = batch;
