/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule QuyuSub_viewer.graphql
 * @generated SignedSource<<0935933453a22996ba611177e5a5af48>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type QuyuSub_viewer = {
  id: string;
  subQuyu?: ?Array<?QuyuSub_viewer_subQuyu>;
};

export type QuyuSub_viewer_subQuyu = {
  id: string;
  name?: ?string;
  code?: ?string;
  isLeaf?: ?boolean;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "code",
      "type": "String"
    },
    {
      "kind": "RootArgument",
      "name": "skip",
      "type": "Boolean"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "QuyuSub_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "Condition",
      "passingValue": false,
      "condition": "skip",
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": [
            {
              "kind": "Variable",
              "name": "code",
              "variableName": "code",
              "type": "String"
            }
          ],
          "concreteType": "Quyu",
          "name": "subQuyu",
          "plural": true,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "code",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "isLeaf",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ]
    }
  ],
  "type": "User"
};

module.exports = fragment;
