/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DraftsDelMutation.graphql
 * @generated SignedSource<<0d35b965eaa02c218f5e4b3208a6d2e9>>
 * @relayHash ac6e1a21278d84b850f124ce62e689f6
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type DraftMutationInput = {
  order?: ?number;
  id?: ?string;
};

export type DraftsDelMutationResponse = {
  distroyedId?: ?string;
  error?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

/*
mutation DraftsDelMutation(
  $input: DraftMutationInput!
) {
  DraftMutation(input: $input) {
    distroyedId
    error
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "DraftMutationInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "DraftsDelMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "DraftMutationInput!"
          }
        ],
        "concreteType": "DraftMutationPayload",
        "name": "DraftMutation",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "distroyedId",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "error",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "DraftsDelMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "DraftMutationInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "DraftsDelMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "DraftMutationInput!"
          }
        ],
        "concreteType": "DraftMutationPayload",
        "name": "DraftMutation",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "distroyedId",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "error",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation DraftsDelMutation(\n  $input: DraftMutationInput!\n) {\n  DraftMutation(input: $input) {\n    distroyedId\n    error\n  }\n}\n"
};

module.exports = batch;
