/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SearchResult_viewer.graphql
 * @generated SignedSource<<9d6636de623c98c7d2e26288ee589639>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type SearchResult_viewer = {
  autocomplete?: ?SearchResult_viewer_autocomplete;
};

export type SearchResult_viewer_autocomplete_names = {
  article?: ?string;
  name?: ?string;
  title?: ?string;
  createdAt?: ?string;
};

export type SearchResult_viewer_autocomplete_titles = {
  article?: ?string;
  name?: ?string;
  title?: ?string;
  createdAt?: ?string;
};

export type SearchResult_viewer_autocomplete = {
  names?: ?Array<?SearchResult_viewer_autocomplete_names>;
  titles?: ?Array<?SearchResult_viewer_autocomplete_titles>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "token",
      "type": "String!"
    },
    {
      "kind": "RootArgument",
      "name": "size",
      "type": "Int!"
    },
    {
      "kind": "RootArgument",
      "name": "skip",
      "type": "Boolean"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "SearchResult_viewer",
  "selections": [
    {
      "kind": "Condition",
      "passingValue": false,
      "condition": "skip",
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": [
            {
              "kind": "Variable",
              "name": "size",
              "variableName": "size",
              "type": "Int!"
            },
            {
              "kind": "Variable",
              "name": "token",
              "variableName": "token",
              "type": "String!"
            }
          ],
          "concreteType": "AutoCompleteDatasource",
          "name": "autocomplete",
          "plural": false,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "AutoCompleteRecord",
              "name": "names",
              "plural": true,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "article",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "title",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "createdAt",
                  "storageKey": null
                }
              ],
              "storageKey": null
            },
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "AutoCompleteRecord",
              "name": "titles",
              "plural": true,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "article",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "title",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "createdAt",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ]
    }
  ],
  "type": "User"
};

module.exports = fragment;
