/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule HomeRefetchQuery.graphql
 * @generated SignedSource<<ac832e29123817a6cf53e35b071aee88>>
 * @relayHash d9abe49cde87a41983bf3d86f575689d
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query HomeRefetchQuery(
  $count: Int
  $cursor: String
  $conditions: ArticleFilters
  $sorters: [QuerySorter]
  $width: Int!
  $height: Int!
  $m: String
) {
  viewer {
    ...ArticlePagination_viewer
    id
  }
}

fragment ArticlePagination_viewer on User {
  id
  articles(first: $count, after: $cursor, conditions: $conditions, sorters: $sorters) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        gender
        id
        attachments_wh(width: $width, height: $height, m: $m)
        submit
        title
        categories
        name
        education
        key
        birthday
        homePlace {
          province
          city
          area
        }
        jobs
        marriage
        children
        knowledge
        createdAt
        __typename
      }
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "count",
        "type": "Int",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "cursor",
        "type": "String",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "conditions",
        "type": "ArticleFilters",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "sorters",
        "type": "[QuerySorter]",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "width",
        "type": "Int!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "height",
        "type": "Int!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "m",
        "type": "String",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "HomeRefetchQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "ArticlePagination_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "HomeRefetchQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "count",
        "type": "Int",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "cursor",
        "type": "String",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "conditions",
        "type": "ArticleFilters",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "sorters",
        "type": "[QuerySorter]",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "width",
        "type": "Int!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "height",
        "type": "Int!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "m",
        "type": "String",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "HomeRefetchQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "after",
                "variableName": "cursor",
                "type": "String"
              },
              {
                "kind": "Variable",
                "name": "conditions",
                "variableName": "conditions",
                "type": "ArticleFilters"
              },
              {
                "kind": "Variable",
                "name": "first",
                "variableName": "count",
                "type": "Int"
              },
              {
                "kind": "Variable",
                "name": "sorters",
                "variableName": "sorters",
                "type": "[QuerySorter]"
              }
            ],
            "concreteType": "ArticleConnection",
            "name": "articles",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "PageInfo",
                "name": "pageInfo",
                "plural": false,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "startCursor",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "endCursor",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "hasNextPage",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "hasPreviousPage",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "ArticleEdge",
                "name": "edges",
                "plural": true,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "cursor",
                    "storageKey": null
                  },
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "Article",
                    "name": "node",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "key",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "gender",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": [
                          {
                            "kind": "Variable",
                            "name": "height",
                            "variableName": "height",
                            "type": "Int!"
                          },
                          {
                            "kind": "Variable",
                            "name": "m",
                            "variableName": "m",
                            "type": "String"
                          },
                          {
                            "kind": "Variable",
                            "name": "width",
                            "variableName": "width",
                            "type": "Int!"
                          }
                        ],
                        "name": "attachments_wh",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "submit",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "title",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "categories",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "name",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "education",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "id",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "birthday",
                        "storageKey": null
                      },
                      {
                        "kind": "LinkedField",
                        "alias": null,
                        "args": null,
                        "concreteType": "HomePlace",
                        "name": "homePlace",
                        "plural": false,
                        "selections": [
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "province",
                            "storageKey": null
                          },
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "city",
                            "storageKey": null
                          },
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "area",
                            "storageKey": null
                          }
                        ],
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "jobs",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "marriage",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "children",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "knowledge",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "createdAt",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "__typename",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "LinkedHandle",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "after",
                "variableName": "cursor",
                "type": "String"
              },
              {
                "kind": "Variable",
                "name": "conditions",
                "variableName": "conditions",
                "type": "ArticleFilters"
              },
              {
                "kind": "Variable",
                "name": "first",
                "variableName": "count",
                "type": "Int"
              },
              {
                "kind": "Variable",
                "name": "sorters",
                "variableName": "sorters",
                "type": "[QuerySorter]"
              }
            ],
            "handle": "connection",
            "name": "articles",
            "key": "ArticlePagination_articles",
            "filters": [
              "conditions",
              "sorters"
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query HomeRefetchQuery(\n  $count: Int\n  $cursor: String\n  $conditions: ArticleFilters\n  $sorters: [QuerySorter]\n  $width: Int!\n  $height: Int!\n  $m: String\n) {\n  viewer {\n    ...ArticlePagination_viewer\n    id\n  }\n}\n\nfragment ArticlePagination_viewer on User {\n  id\n  articles(first: $count, after: $cursor, conditions: $conditions, sorters: $sorters) {\n    pageInfo {\n      startCursor\n      endCursor\n      hasNextPage\n      hasPreviousPage\n    }\n    edges {\n      cursor\n      node {\n        gender\n        id\n        attachments_wh(width: $width, height: $height, m: $m)\n        submit\n        title\n        categories\n        name\n        education\n        key\n        birthday\n        homePlace {\n          province\n          city\n          area\n        }\n        jobs\n        marriage\n        children\n        knowledge\n        createdAt\n        __typename\n      }\n    }\n  }\n}\n"
};

module.exports = batch;
